apiVersion: v1
kind: Service
metadata:
  name: service-provisioning-and-automation
  labels:
    app: service-provisioning-and-automation
spec:
  type: NodePort
  selector:
    app: service-provisioning-and-automation
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
