---
- name: Add tmp.mount.d folder for tmpfs configuration
  file:
    path: /etc/systemd/system/tmp.mount.d
    state: directory

- name: Change tmpfs size to 1G for Jenkins builds
  copy:
    dest: /etc/systemd/system/tmp.mount.d/override.conf
    content: |
      [Mount]
      Options=mode=1777,strictatime,nosuid,nodev,size=1G,nr_inodes=1m

- name: Reload systemd to apply tmpfs changes
  systemd:
    daemon_reload: yes
    state: restarted
    name: tmp.mount

- name: Add Jenkins repo
  command: >
    dnf config-manager --add-repo https://pkg.jenkins.io/rpm-stable/jenkins.repo
  args:
    creates: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins and dependencies
  dnf:
    name:
      - fontconfig
      - java-21-amazon-corretto
      - jenkins
    state: present

- name: Install build tools for Jenkins
  dnf:
    name:
      - git
      - docker
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes
