---
- name: Add swap file for Jenkins
  command: >
    fallocate -l 1.5G /swapfile && 
    chmod 600 /swapfile && 
    mkswap /swapfile && 
    swapon /swapfile &&
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  args:
    creates: /swapfile

- name: Add Jenkins repo
  command: >
    dnf config-manager --add-repo https://pkg.jenkins.io/rpm-stable/jenkins.repo
  args:
    creates: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins and dependencies
  dnf:
    name:
      - fontconfig
      - java-21-amazon-corretto
      - jenkins
    state: present

- name: Install build tools for Jenkins
  dnf:
    name:
      - git
      - docker
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add jenkins to docker group
  user:
    name: jenkins
    groups: docker
    append: yes

- name: Enable and start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: yes
    daemon_reload: yes
